version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bugbounty
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
